# Generated by Django 4.0.5 on 2022-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_patient_address2_remove_patient_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='exp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Post surgical case', 'Post surgical case'), ('Elderly care', 'Elderly care'), ('Wound care infections', 'Wound care infections'), ('Cancer', 'Cancer')], default='Cardiologist', max_length=50),
        ),
    ]
