# Generated by Django 4.0.5 on 2022-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patientdischargedetails_exp_alter_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='exp',
        ),
        migrations.AddField(
            model_name='doctor',
            name='exp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
